# Generated by Django 4.0.2 on 2024-07-12 17:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_categoria', '0001_initial'),
        ('app_reg_empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecSiembraEnc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Registro ')),
                ('fecha_compra', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Compra ')),
                ('fecha_transferencia', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Transferencia')),
                ('observacion', models.CharField(blank=True, default='Sin Novedades, Ninguna Observación', max_length=550, null=True, verbose_name='Observación')),
                ('prod_cantidad', models.TextField(blank=True, null=True, verbose_name='Prod Cantidad')),
                ('resul_oper', models.TextField(blank=True, null=True, verbose_name='Resultado Proceso')),
                ('tot_comp', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('tip_precSiembra', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Precria Siembra Enc',
                'verbose_name_plural': 'Precrias Siembras Enc',
                'db_table': 'db_prec_siembra_enc',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PrecSiembraCuerp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Compra ')),
                ('fecha_transferencia', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Transferencia ')),
                ('comp_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('comp_2', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('comp_3', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('tot_comp', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('prod_cantidad', models.TextField(blank=True, null=True, verbose_name='Prod Cantidad')),
                ('dias', models.IntegerField(default=0)),
                ('siembra', models.DecimalField(decimal_places=3, default=0.0, max_digits=9)),
                ('costo_larva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('dia_por_hect', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('prod_cantidad_proceso', models.TextField(blank=True, null=True, verbose_name='Cantidad Prod Proceso')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('resul_oper', models.TextField(blank=True, null=True, verbose_name='Resultado Proceso')),
                ('observacion', models.CharField(blank=True, default='Sin Novedades, Ninguna Observación', max_length=550, null=True, verbose_name='Observación')),
                ('fecha_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_corrida.precsiembraenc')),
                ('piscina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_reg_empresa.piscinas', verbose_name='Empresa')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_categoria.producto')),
            ],
            options={
                'verbose_name': 'Precria Siembra Cuerpo',
                'verbose_name_plural': 'Precrias Siembras Cuerpo',
                'db_table': 'db_prec_siembra_cuerp',
                'ordering': ['id'],
            },
        ),
    ]
