# Generated by Django 5.2.4 on 2026-03-06 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_categoria', '0001_initial'),
        ('app_corrida', '0001_initial'),
        ('app_piscinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='precsiembracuerp',
            name='piscina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_piscinas.piscinas', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='precsiembracuerp',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_categoria.producto'),
        ),
        migrations.AddField(
            model_name='precsiembracuerp',
            name='fecha_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_corrida.precsiembraenc'),
        ),
    ]
