# Generated by Django 5.2.4 on 2025-08-09 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_public', models.BooleanField(default=False, verbose_name='Es Público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_folders', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='app_filemanager.folder', verbose_name='Carpeta Padre')),
            ],
            options={
                'verbose_name': 'Carpeta',
                'verbose_name_plural': 'Carpetas',
                'ordering': ['name'],
                'permissions': [('can_view_folder', 'Can view folder'), ('can_edit_folder', 'Can edit folder'), ('can_delete_folder', 'Can delete folder'), ('can_share_folder', 'Can share folder')],
                'unique_together': {('name', 'parent', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('file', models.FileField(upload_to='filemanager/uploads/%Y/%m/%d/', verbose_name='Archivo')),
                ('size', models.BigIntegerField(default=0, verbose_name='Tamaño')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Archivo')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo MIME')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_public', models.BooleanField(default=False, verbose_name='Es Público')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Descargas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_files', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app_filemanager.folder', verbose_name='Carpeta')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'ordering': ['-created_at'],
                'permissions': [('can_view_file', 'Can view file'), ('can_download_file', 'Can download file'), ('can_edit_file', 'Can edit file'), ('can_delete_file', 'Can delete file'), ('can_share_file', 'Can share file')],
            },
        ),
        migrations.CreateModel(
            name='SharedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('view', 'Solo Ver'), ('download', 'Ver y Descargar'), ('edit', 'Ver, Descargar y Editar')], default='view', max_length=10, verbose_name='Nivel de Permiso')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token')),
                ('is_public', models.BooleanField(default=False, verbose_name='Es Público')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to='app_filemanager.file', verbose_name='Archivo')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to='app_filemanager.folder', verbose_name='Carpeta')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_shares', to=settings.AUTH_USER_MODEL, verbose_name='Compartido por')),
                ('shared_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to=settings.AUTH_USER_MODEL, verbose_name='Compartido con')),
            ],
            options={
                'verbose_name': 'Enlace Compartido',
                'verbose_name_plural': 'Enlaces Compartidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FilePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('read', 'Solo Lectura'), ('write', 'Lectura y Escritura'), ('admin', 'Acceso Total')], default='read', max_length=10, verbose_name='Nivel de Permiso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to='app_filemanager.file', verbose_name='Archivo')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_file_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Otorgado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Permiso de Archivo',
                'verbose_name_plural': 'Permisos de Archivos',
                'ordering': ['-created_at'],
                'unique_together': {('file', 'user')},
            },
        ),
        migrations.CreateModel(
            name='FolderPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('read', 'Solo Lectura'), ('write', 'Lectura y Escritura'), ('admin', 'Acceso Total')], default='read', max_length=10, verbose_name='Nivel de Permiso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to='app_filemanager.folder', verbose_name='Carpeta')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Otorgado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Permiso de Carpeta',
                'verbose_name_plural': 'Permisos de Carpetas',
                'ordering': ['-created_at'],
                'unique_together': {('folder', 'user')},
            },
        ),
    ]
