# Generated by Django 5.2.4 on 2025-08-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_filemanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=900, upload_to='filemanager/uploads/%Y/%m/%d/', verbose_name='Archivo'),
        ),
    ]
