# Generated by Django 4.0.2 on 2024-07-12 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_contabilidad_planCuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13, unique=True, verbose_name='RUC ')),
                ('razon_soc', models.CharField(max_length=250, unique=True, verbose_name='Razon Social ')),
                ('nombre_com', models.CharField(blank=True, max_length=400, null=True, verbose_name='Nombre Comercial ')),
                ('actividad_com', models.CharField(blank=True, max_length=350, null=True, verbose_name='Actividad Comercial ')),
                ('grupo', models.CharField(max_length=50, verbose_name='Grupo ')),
                ('telef1', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefono 1 ')),
                ('telef2', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefono 2 ')),
                ('mail', models.TextField(blank=True, null=True, verbose_name='Correo ')),
                ('direccion1', models.CharField(blank=True, max_length=350, null=True, verbose_name='Direccion 1 ')),
                ('direccion2', models.CharField(blank=True, max_length=350, null=True, verbose_name='Direccion 2 ')),
                ('direccion3', models.CharField(blank=True, max_length=350, null=True, verbose_name='Direccion 3 ')),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad ')),
                ('estado', models.CharField(default=True, max_length=50, verbose_name='Estado ')),
                ('cod_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_contabilidad_planCuentas.plancuenta')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'tb_proveedor',
                'ordering': ['id'],
            },
        ),
    ]
