# Generated by Django 5.2.4 on 2026-03-05 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=400, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'tb_categoria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=400, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Linea',
                'verbose_name_plural': 'Lineas',
                'db_table': 'tb_linea',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre ')),
                ('gramaje', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gramaje para aplicacion en Dieta')),
                ('gramaje_precria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gramaje para aplicacion en Precriadero')),
                ('presentacion', models.CharField(blank=True, max_length=400, null=True, verbose_name='Presentacion ')),
                ('peso_presentacion', models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True, verbose_name='Peso de la Presentacion ')),
                ('unid_medida', models.CharField(blank=True, max_length=400, null=True, verbose_name='Unidad de Medida de la Presentación ')),
                ('unid_aplicacion', models.CharField(blank=True, max_length=400, null=True, verbose_name='Aplicación en ')),
                ('minimo_stock', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=19, null=True, verbose_name='Ingrese el Stock Mínimo ')),
                ('costo', models.DecimalField(decimal_places=10, default=0.0, max_digits=19, verbose_name='Valor de Producto ')),
                ('costo_aplicacion', models.DecimalField(decimal_places=10, default=0.0, max_digits=19, verbose_name='Costo de Aplicacion del Producto')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado ')),
                ('aplic_directa', models.BooleanField(default=False, verbose_name='Aplicación Directa ')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d', verbose_name='Seleccionar Imagen ')),
                ('inventoried', models.BooleanField(default=True, verbose_name='¿Es inventariado?')),
                ('stock', models.IntegerField(default=0, verbose_name='Ingrese el Stock')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_categoria.categoria')),
                ('descripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_categoria.linea', verbose_name='Sub-Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'tb_producto',
                'ordering': ['id'],
            },
        ),
    ]
