# Generated by Django 4.0.2 on 2025-06-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_categoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='inventoried',
            field=models.BooleanField(default=True, verbose_name='¿Es inventariado?'),
        ),
    ]
