# Generated by Django 4.0.2 on 2025-06-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_categoria', '0002_producto_inventoried'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Costo'),
        ),
    ]
