# Generated by Django 4.0.2 on 2025-07-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_categoria', '0003_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='costo_aplicacion',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19, verbose_name='Costo de Aplicacion del Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Ingrese el Stock'),
        ),
    ]
