# Generated by Django 4.0.2 on 2025-07-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_categoria', '0004_alter_producto_costo_aplicacion_alter_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='minimo_stock',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=19, null=True, verbose_name='Ingrese el Stock Mínimo '),
        ),
    ]
