# Generated by Django 5.2.4 on 2025-10-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_categoria', '0005_alter_producto_minimo_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='barcode/%Y/%m/%d', verbose_name='Código de barra'),
        ),
        migrations.AddField(
            model_name='producto',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='producto',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de Compra'),
        ),
        migrations.AddField(
            model_name='producto',
            name='pvp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de Venta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='with_tax',
            field=models.BooleanField(default=True, verbose_name='¿Se cobra impuesto?'),
        ),
    ]
