# Generated by Django 4.0.2 on 2025-11-20 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad_planCuentas', '0017_alter_anexotransaccional_estab'),
        ('app_categoria', '0005_alter_producto_minimo_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cod_contable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_contabilidad_planCuentas.plancuenta'),
        ),
    ]
