# Generated by Django 4.0.2 on 2025-11-20 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_categoria', '0006_producto_cod_contable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cod_contable',
        ),
    ]
