# Generated by Django 5.2.4 on 2025-10-15 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_categoria', '0006_producto_barcode_producto_code_producto_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='code',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='price',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='pvp',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='with_tax',
        ),
    ]
