# Generated by Django 5.2.4 on 2025-11-21 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_categoria', '0007_remove_producto_barcode_remove_producto_code_and_more'),
        ('app_categoria', '0007_remove_producto_cod_contable'),
    ]

    operations = [
    ]
