# Generated by Django 5.2.4 on 2026-01-07 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_categoria', '0008_merge_20251121_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=400, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Linea',
                'verbose_name_plural': 'Lineas',
                'db_table': 'tb_linea',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_categoria.linea', verbose_name='Sub-Categoría'),
        ),
    ]
