# Generated by Django 5.2.4 on 2026-01-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_categoria', '0010_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='gramaje_precria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gramaje Precria '),
        ),
        migrations.AlterField(
            model_name='producto',
            name='gramaje',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gramaje Dieta'),
        ),
    ]
