# Generated by Django 4.0.2 on 2026-02-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_categoria', '0011_producto_gramaje_precria_alter_producto_gramaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='gramaje',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gramaje para aplicacion en Dieta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='gramaje_precria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gramaje para aplicacion en Precriadero'),
        ),
    ]
