# Generated by Django 5.2.4 on 2026-03-06 02:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_contabilidad_planCuentas', '0002_initial'),
        ('app_reg_empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNoteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('cant', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('price_with_vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('dscto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total_dscto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
            options={
                'verbose_name': 'Detalle Devolución Ventas',
                'verbose_name_plural': 'Detalle Devoluciones Ventas',
                'db_table': 'tb_notCreditodetalle',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('motive', models.CharField(blank=True, max_length=300, null=True, verbose_name='Motivo')),
                ('voucher_number', models.CharField(max_length=9, verbose_name='Número de comprobante')),
                ('voucher_number_full', models.CharField(max_length=20, verbose_name='Número de comprobante completo')),
                ('subtotal_12', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Subtotal')),
                ('subtotal_0', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Subtotal 0%')),
                ('total_dscto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Valor del descuento')),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Iva')),
                ('total_iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Valor de iva')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Total a pagar')),
                ('environment_type', models.PositiveIntegerField(choices=[(1, 'PRUEBAS'), (2, 'PRODUCCIÓN')], default=1)),
                ('access_code', models.CharField(blank=True, max_length=49, null=True, verbose_name='Clave de acceso')),
                ('authorization_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de autorización')),
                ('xml_authorized', models.FileField(blank=True, null=True, upload_to='', verbose_name='XML Autorizado')),
                ('pdf_authorized', models.FileField(blank=True, null=True, upload_to='pdf_authorized/%Y/%m/%d', verbose_name='PDF Autorizado')),
                ('create_electronic_invoice', models.BooleanField(default=True, verbose_name='Crear factura electrónica')),
                ('status', models.CharField(choices=[('without_authorizing', 'Sin Autorizar'), ('authorized', 'Autorizada'), ('authorized_and_sent_by_email', 'Autorizada y enviada por email'), ('canceled', 'Anulado'), ('sequential_registered_error', 'Error de secuencial registrado')], default='without_authorizing', max_length=50, verbose_name='Estado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_reg_empresa.empresa', verbose_name='Compañia')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_contabilidad_planCuentas.recibo', verbose_name='Tipo de comprobante')),
            ],
            options={
                'verbose_name': 'Nota de Credito',
                'verbose_name_plural': 'Notas de Credito',
                'db_table': 'tb_notCredito',
                'ordering': ['id'],
            },
        ),
    ]
