# Generated by Django 5.2.4 on 2026-03-06 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_notaCredito', '0001_initial'),
        ('app_piscinas', '0001_initial'),
        ('app_venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_venta.sale', verbose_name='Venta'),
        ),
        migrations.AddField(
            model_name='creditnotedetail',
            name='credit_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_notaCredito.creditnote'),
        ),
        migrations.AddField(
            model_name='creditnotedetail',
            name='piscina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_piscinas.piscinas'),
        ),
        migrations.AddField(
            model_name='creditnotedetail',
            name='sale_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_venta.saledetail'),
        ),
    ]
