# Generated by Django 4.0.2 on 2025-08-28 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reg_empresa', '0007_piscinas_inventoried'),
        ('app_notaCredito', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnotedetail',
            name='product',
        ),
        migrations.AddField(
            model_name='creditnotedetail',
            name='piscina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_reg_empresa.piscinas'),
        ),
    ]
