# Generated by Django 5.2.4 on 2026-03-06 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_contabilidad_planCuentas', '0002_initial'),
        ('app_reg_empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piscinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.CharField(max_length=150, unique=True, verbose_name='Orden de las Piscinas ')),
                ('numero', models.CharField(max_length=150, unique=True, verbose_name='Número de Piscina ')),
                ('hect', models.CharField(max_length=150, verbose_name='Hectáreas de Dimensiones')),
                ('pis', models.BooleanField(default=True, verbose_name='Piscina ')),
                ('prec', models.BooleanField(default=False, verbose_name='Precria ')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado ')),
                ('inventoried', models.BooleanField(default=True, verbose_name='¿Es inventariado?')),
                ('with_tax', models.BooleanField(default=True, verbose_name='¿Se cobra impuesto?')),
                ('cuenta_suministros', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piscinas_suministros', to='app_contabilidad_planCuentas.plancuenta', verbose_name='Cuenta de Suministros')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reg_empresa.empresa', verbose_name='Empresa ')),
                ('plan_cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piscinas', to='app_contabilidad_planCuentas.plancuenta', verbose_name='Plan de Cuentas')),
            ],
            options={
                'verbose_name': 'Piscina',
                'verbose_name_plural': 'Piscinas',
                'db_table': 'tb_piscina',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PiscinaHistorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fue_piscina', models.BooleanField(default=False)),
                ('fue_precria', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('piscina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='app_piscinas.piscinas')),
            ],
            options={
                'db_table': 'tb_piscina_historial',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
