# Generated by Django 4.0.2 on 2025-06-09 16:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=13, unique=True, verbose_name='Número de cedula o ruc')),
                ('movil', models.CharField(max_length=10, unique=True, verbose_name='Teléfono')),
                ('nacimiento', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('direccion', models.CharField(max_length=500, verbose_name='Dirección')),
                ('identification_type', models.CharField(choices=[('05', 'CEDULA'), ('04', 'RUC'), ('06', 'PASAPORTE'), ('07', 'VENTA A CONSUMIDOR FINAL*'), ('08', 'IDENTIFICACION DELEXTERIOR*')], default='05', max_length=30, verbose_name='Tipo de identificación')),
                ('send_email_invoice', models.BooleanField(default=True, verbose_name='¿Enviar email de factura?')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
