# Generated by Django 4.0.2 on 2025-06-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nacimiento',
            new_name='fecha_nacimiento',
        ),
    ]
