# Generated by Django 4.0.2 on 2025-06-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_rename_nacimiento_cliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='fecha_nacimiento',
            new_name='nacimiento',
        ),
    ]
