# Generated by Django 5.2.4 on 2026-03-06 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_costoutilidad', '0001_initial'),
        ('app_piscinas', '0001_initial'),
        ('app_proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='piscina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='app_piscinas.piscinas', verbose_name='Piscina'),
        ),
        migrations.AddField(
            model_name='costooperativo',
            name='piscina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='app_piscinas.piscinas', verbose_name='Piscina'),
        ),
        migrations.AddField(
            model_name='costooperativo',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_operativos', to='app_proveedor.proveedor'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producciones', to='app_costoutilidad.ciclo', verbose_name='Ciclo'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='piscina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producciones', to='app_piscinas.piscinas', verbose_name='Piscina'),
        ),
        migrations.AddField(
            model_name='costooperativo',
            name='tipo_costo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costos', to='app_costoutilidad.tipocosto', verbose_name='Tipo de Costo'),
        ),
    ]
