# Generated by Django 4.0.2 on 2026-02-02 21:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_contabilidad_planCuentas', '0017_alter_anexotransaccional_estab'),
        ('app_compra', '0001_initial'),
        ('app_reg_empresa', '0010_alter_piscinas_cuenta_suministros_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=9)),
                ('voucher_number_full', models.CharField(max_length=20)),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_iva_retained', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_renta_retained', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_retained', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('AUTHORIZED', 'Autorizado'), ('REJECTED', 'Rechazado')], default='DRAFT', max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reg_empresa.empresa')),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app_compra.purchase')),
                ('receipt', models.ForeignKey(limit_choices_to={'voucher_type': '07'}, on_delete=django.db.models.deletion.PROTECT, to='app_contabilidad_planCuentas.recibo')),
            ],
        ),
        migrations.CreateModel(
            name='RetentionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('IVA', 'IVA'), ('RENTA', 'RENTA')], max_length=10)),
                ('tax_code', models.CharField(max_length=10)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_retencion.retention')),
            ],
        ),
    ]
