# Generated by Django 4.0.2 on 2026-02-02 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_proveedor', '0001_initial'),
        ('app_retencion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retention',
            name='purchase',
        ),
        migrations.AddField(
            model_name='retention',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_proveedor.proveedor'),
        ),
        migrations.AlterField(
            model_name='retention',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('AUTHORIZED', 'Autorizado'), ('REJECTED', 'Rechazado')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='retentiondetail',
            name='retention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app_retencion.retention'),
        ),
        migrations.AlterField(
            model_name='retentiondetail',
            name='value',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
