# Generated by Django 4.0.2 on 2026-02-02 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad_planCuentas', '0017_alter_anexotransaccional_estab'),
        ('app_retencion', '0002_remove_retention_purchase_retention_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retention',
            name='receipt',
            field=models.ForeignKey(blank=True, limit_choices_to={'voucher_type': '07'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_contabilidad_planCuentas.recibo'),
        ),
    ]
