# Generated by Django 4.0.2 on 2026-02-03 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad_planCuentas', '0017_alter_anexotransaccional_estab'),
        ('app_proveedor', '0001_initial'),
        ('app_reg_empresa', '0010_alter_piscinas_cuenta_suministros_and_more'),
        ('app_retencion', '0003_alter_retention_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retention',
            name='status',
        ),
        migrations.RemoveField(
            model_name='retention',
            name='total_iva_retained',
        ),
        migrations.RemoveField(
            model_name='retention',
            name='total_renta_retained',
        ),
        migrations.AddField(
            model_name='retention',
            name='access_code',
            field=models.CharField(blank=True, max_length=49, null=True),
        ),
        migrations.AddField(
            model_name='retention',
            name='authorization_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retention',
            name='total_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='retention',
            name='total_renta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='retention',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_reg_empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='retention',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='retention',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_proveedor.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='retention',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_contabilidad_planCuentas.recibo', verbose_name='Comprobante'),
        ),
        migrations.AlterField(
            model_name='retention',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='retention',
            name='total_retained',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='retention',
            name='voucher_number',
            field=models.CharField(default='', max_length=9, verbose_name='Número de comprobante'),
        ),
        migrations.AlterField(
            model_name='retention',
            name='voucher_number_full',
            field=models.CharField(default='', max_length=20, verbose_name='Número de comprobante completo'),
        ),
        migrations.AlterField(
            model_name='retentiondetail',
            name='base',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='retentiondetail',
            name='value',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
