# Generated by Django 4.0.2 on 2026-02-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_retencion', '0004_remove_retention_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retention',
            name='pdf_authorized',
            field=models.FileField(blank=True, null=True, upload_to='retenciones/'),
        ),
    ]
