# Generated by Django 4.0.2 on 2026-02-03 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reg_empresa', '0010_alter_piscinas_cuenta_suministros_and_more'),
        ('app_proveedor', '0001_initial'),
        ('app_contabilidad_planCuentas', '0017_alter_anexotransaccional_estab'),
        ('app_retencion', '0005_retention_pdf_authorized'),
    ]

    operations = [
        migrations.AddField(
            model_name='retentiondetail',
            name='comp_pago_cuota',
            field=models.CharField(choices=[('OPCION_1', 'OPCIÓN 1'), ('OPCION_2', 'OPCIÓN 2'), ('OPCION_3', 'OPCIÓN 3'), ('OPCION_4', 'OPCIÓN 4'), ('OPCION_5', 'OPCIÓN 5'), ('OPCION_6', 'OPCIÓN 6'), ('OPCION_7', 'OPCIÓN 7'), ('OPCION_8', 'OPCIÓN 8'), ('OPCION_9', 'OPCIÓN 9'), ('OPCION_10', 'OPCIÓN 10'), ('OPCION_11', 'OPCIÓN 11'), ('COMP_PAGO_CUOTA', 'COMP. PAGO CUOTA'), ('OPCION_13', 'OPCIÓN 13'), ('OPCION_14', 'OPCIÓN 14'), ('OPCION_15', 'OPCIÓN 15')], default='OPCION_1', help_text="Seleccione una opción, la opción 12 es 'COMP. PAGO CUOTA'", max_length=20, verbose_name='COMP. PAGO CUOTA'),
        ),
        migrations.AddField(
            model_name='retentiondetail',
            name='numero_15_digitos',
            field=models.CharField(blank=True, help_text='Ingrese un número de hasta 15 dígitos', max_length=15, null=True, verbose_name='Número (15 dígitos máximo)'),
        ),
        migrations.AlterField(
            model_name='retention',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_reg_empresa.empresa'),
        ),
        migrations.AlterField(
            model_name='retention',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_proveedor.proveedor'),
        ),
        migrations.AlterField(
            model_name='retention',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_contabilidad_planCuentas.recibo'),
        ),
        migrations.AlterField(
            model_name='retention',
            name='voucher_number',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='retention',
            name='voucher_number_full',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
