# Generated by Django 4.0.2 on 2026-02-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_retencion', '0006_retentiondetail_comp_pago_cuota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retention',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
