# Generated by Django 4.0.2 on 2026-02-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_retencion', '0007_retention_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retention',
            name='voucher_number',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='retention',
            name='voucher_number_full',
            field=models.CharField(max_length=20),
        ),
    ]
