# Generated by Django 4.0.2 on 2026-02-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_retencion', '0008_alter_retention_voucher_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retention',
            name='xml_authorized',
            field=models.FileField(blank=True, null=True, upload_to='retenciones/xml/'),
        ),
        migrations.AlterField(
            model_name='retention',
            name='pdf_authorized',
            field=models.FileField(blank=True, null=True, upload_to='retenciones/pdf/'),
        ),
    ]
