# Generated by Django 4.0.2 on 2026-02-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_retencion', '0009_retention_xml_authorized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retention',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
