# Generated by Django 4.0.2 on 2026-02-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_retencion', '0010_retention_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retention',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
