# Generated by Django 5.2.4 on 2026-03-06 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_categoria', '0001_initial'),
        ('app_compra', '0001_initial'),
        ('app_proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_proveedor.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_categoria.producto'),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_compra.purchase'),
        ),
    ]
