# Generated by Django 4.0.2 on 2026-06-16 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_reg_empresa', '0010_alter_piscinas_cuenta_suministros_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaLarva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_larva_sembrada', models.DateField()),
                ('cantidad_larva_sembrada', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('fecha_siembra_piscina', models.DateField()),
                ('laboratorio', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transferencia_larva',
            },
        ),
        migrations.CreateModel(
            name='DetalleTransferenciaLarva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde_piscina', models.CharField(max_length=50)),
                ('maduracion', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=50)),
                ('hectareas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('animales_sembrados', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('peso_siembra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('animales_ha', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('edad', models.IntegerField(default=0)),
                ('total_transferido', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('porcentaje_sobrevivencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aguaje', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_guia', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('hacia_piscina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reg_empresa.piscinas')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_seguimiento.transferencialarva')),
            ],
            options={
                'db_table': 'detalle_transferencia_larva',
            },
        ),
    ]
