# Generated by Django 4.0.2 on 2026-06-17 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalletransferencialarva',
            options={'ordering': ['id'], 'verbose_name': 'Detalle Transferencia', 'verbose_name_plural': 'Detalles Transferencia'},
        ),
        migrations.AlterModelOptions(
            name='transferencialarva',
            options={'ordering': ['-id'], 'verbose_name': 'Transferencia Larva', 'verbose_name_plural': 'Transferencias Larvas'},
        ),
    ]
