# Generated by Django 5.2.4 on 2025-12-10 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_contabilidad_planCuentas', '0017_alter_anexotransaccional_estab'),
        ('app_reg_empresa', '0008_piscinas_cuenta_suministros_piscinas_plan_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagoOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Forma de Pago')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('codigo', models.CharField(blank=True, help_text='Código para identificación rápida', max_length=20, null=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': 'Formas de Pago',
                'db_table': 'tb_forma_pago_opcion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Tipo de Pago')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tipo de Pago',
                'verbose_name_plural': 'Tipos de Pago',
                'db_table': 'tb_tipo_pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Anticipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caja', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('SECUNDARIA', 'Secundaria')], default='PRINCIPAL', max_length=50, verbose_name='Caja')),
                ('tipo_cliente', models.CharField(choices=[('CLIENTE', 'Cliente'), ('PROVEEDOR', 'Proveedor')], default='CLIENTE', max_length=50, verbose_name='Tipo')),
                ('tipo_identificacion', models.CharField(choices=[('CEDULA', 'Cédula'), ('RUC', 'RUC'), ('PASAPORTE', 'Pasaporte')], default='CEDULA', max_length=50, verbose_name='Tipo Identificación')),
                ('identificacion', models.CharField(max_length=20, verbose_name='Identificación')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Comercial')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('celular', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto')),
                ('concepto', models.TextField(verbose_name='Concepto')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('categoria_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_contabilidad_planCuentas.plancuenta', verbose_name='Categoría Contable')),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anticipos_otorgados', to='app_reg_empresa.empresa', verbose_name='Centro de Costo (Empresa)')),
            ],
            options={
                'verbose_name': 'Anticipo',
                'verbose_name_plural': 'Anticipos',
                'db_table': 'tb_anticipo',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor')),
                ('referencia', models.CharField(blank=True, help_text='Número de cheque, transferencia, etc.', max_length=100, null=True, verbose_name='Referencia')),
                ('banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('anticipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_pago', to='app_anticipos.anticipo', verbose_name='Anticipo')),
                ('forma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_anticipos.formapagoopcion', verbose_name='Forma')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_anticipos.tipopago', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': 'Formas de Pago',
                'db_table': 'tb_forma_pago',
                'ordering': ['id'],
            },
        ),
    ]
