# Generated by Django 5.2.4 on 2026-03-06 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_anticipo', '0001_initial'),
        ('app_contabilidad_planCuentas', '0001_initial'),
        ('app_reg_empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anticipo',
            name='categoria_contable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_contabilidad_planCuentas.plancuenta', verbose_name='Categoría Contable'),
        ),
        migrations.AddField(
            model_name='anticipo',
            name='centro_costo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anticipos_otorgados', to='app_reg_empresa.empresa', verbose_name='Centro de Costo (Empresa)'),
        ),
        migrations.AddField(
            model_name='formapago',
            name='anticipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_pago', to='app_anticipo.anticipo', verbose_name='Anticipo'),
        ),
        migrations.AddField(
            model_name='formapago',
            name='forma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_anticipo.formapagoopcion', verbose_name='Forma'),
        ),
        migrations.AddField(
            model_name='formapago',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_anticipo.tipopago', verbose_name='Tipo'),
        ),
    ]
