# Generated by Django 4.0.2 on 2025-07-08 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reg_empresa', '0005_rename_app_cliente_produccion_cliente'),
        ('app_venta', '0003_debtspay_typeexpense_paymentsdebtspay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saledetail',
            name='product',
        ),
        migrations.AddField(
            model_name='saledetail',
            name='piscinas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_reg_empresa.piscinas', verbose_name='Empresa'),
        ),
    ]
