# Generated by Django 4.0.2 on 2025-07-14 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reg_empresa', '0005_rename_app_cliente_produccion_cliente'),
        ('app_venta', '0004_remove_saledetail_product_saledetail_piscinas'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='observacion',
            field=models.TextField(blank=True, default='Sin Novedades', null=True, verbose_name='Observación '),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='piscinas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_reg_empresa.piscinas', verbose_name='Piscinas'),
        ),
    ]
