# Generated by Django 5.2.4 on 2025-08-12 18:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad_planCuentas', '0015_alter_anexotransaccional_receipt_and_more'),
        ('app_venta', '0005_saledetail_observacion_alter_saledetail_piscinas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de registro'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='receipt',
            field=models.ForeignKey(limit_choices_to={'voucher_type__in': ['01', '08']}, on_delete=django.db.models.deletion.PROTECT, to='app_contabilidad_planCuentas.recibo', verbose_name='Tipo de comprobante'),
        ),
    ]
