# Generated by Django 4.0.2 on 2024-08-21 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad_planCuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexotransaccional',
            name='cant_iva_cero',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Cant IVA 0%'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='cant_iva_cien',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Cant IVA 100%'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='cant_iva_cinc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Cant IVA 50%'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='cant_iva_diez',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Cant IVA 10%'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='cant_iva_setn',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Cant IVA 70%'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='cant_iva_treint',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Cant IVA 30%'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='cant_iva_veint',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Cant IVA 20%'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='porcent_ice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Porcentaje ICE'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='ret_fue_iva_anexo_dos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Anexo IVA 2'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='ret_fue_iva_anexo_tres',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Anexo IVA 3'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='ret_fue_iva_anexo_uno',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Anexo IVA 1'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='ret_fue_iva_cero_dos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Base 2 al 0%'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='ret_fue_iva_cero_tres',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Base 3 al 0%'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='ret_fue_iva_cero_uno',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Base 1 al 0%'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='ret_fue_iva_monto_dos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Monto 2'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='ret_fue_iva_monto_tres',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Monto 3'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='ret_fue_iva_monto_uno',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Monto 1'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='ret_fue_iva_porcent_dos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Porcentaje 2'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='ret_fue_iva_porcent_tres',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Porcentaje 3'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='ret_fue_iva_porcent_uno',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Porcentaje 1'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='ret_iva_cero',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Ret IVA 0%'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='ret_iva_cien',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Ret IVA 100%'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='ret_iva_cinc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Ret IVA 50%'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='ret_iva_diez',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Ret IVA 10%'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='ret_iva_setn',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Ret IVA 70%'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='ret_iva_treint',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Ret IVA 30%'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='ret_iva_veint',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Ret IVA 20%'),
        ),
        migrations.AddField(
            model_name='encabezadocuentasplancuenta',
            name='reg_ats',
            field=models.CharField(default='SIN REGISTRO DE ATS', max_length=400, verbose_name='Es ATS'),
        ),
        migrations.AlterField(
            model_name='anexotransaccional',
            name='comp_numero',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Número de comprobante'),
        ),
        migrations.AlterField(
            model_name='anexotransaccional',
            name='comp_numero_full',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de comprobante completo'),
        ),
        migrations.AlterField(
            model_name='anexotransaccional',
            name='create_electronic_document',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Crear documento electrónico'),
        ),
        migrations.AlterField(
            model_name='anexotransaccional',
            name='environment_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'PRUEBAS'), (2, 'PRODUCCIÓN')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='anexotransaccional',
            name='receipt',
            field=models.ForeignKey(blank=True, limit_choices_to={'voucher_type__in': ['01', '08']}, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_contabilidad_planCuentas.recibo', verbose_name='Tipo de comprobante'),
        ),
        migrations.AlterField(
            model_name='anexotransaccional',
            name='reem_numero',
            field=models.CharField(default=0, max_length=9, verbose_name='Número de Reembolso'),
        ),
        migrations.AlterField(
            model_name='anexotransaccional',
            name='reem_numero_full',
            field=models.CharField(default=0, max_length=20, verbose_name='Número de reembolso completo'),
        ),
        migrations.AlterField(
            model_name='anexotransaccional',
            name='ret_numero',
            field=models.CharField(default=0, max_length=9, verbose_name='Número de Retención'),
        ),
        migrations.AlterField(
            model_name='anexotransaccional',
            name='ret_numero_full',
            field=models.CharField(default=0, max_length=20, verbose_name='Número de retención completo'),
        ),
        migrations.AlterField(
            model_name='anexotransaccional',
            name='status',
            field=models.CharField(blank=True, choices=[('without_authorizing', 'Sin Autorizar'), ('authorized', 'Autorizada'), ('authorized_and_sent_by_email', 'Autorizada y enviada por email'), ('canceled', 'Anulado'), ('sequential_registered_error', 'Error de secuencial registrado')], default='without_authorizing', max_length=50, null=True, verbose_name='Estado'),
        ),
    ]
