# Generated by Django 5.2.4 on 2026-03-06 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_contabilidad_planCuentas', '0001_initial'),
        ('app_proveedor', '0001_initial'),
        ('app_reg_empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encabezadocuentasplancuenta',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_proveedor.proveedor', verbose_name='Seleccionar Proveedor '),
        ),
        migrations.AddField(
            model_name='detallecuentasplancuenta',
            name='encabezadocuentaplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_contabilidad_planCuentas.encabezadocuentasplancuenta'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='encabezadocuentaplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_contabilidad_planCuentas.encabezadocuentasplancuenta'),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app_contabilidad_planCuentas.folder'),
        ),
        migrations.AddField(
            model_name='plancuenta',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_reg_empresa.empresa', verbose_name='Empresa '),
        ),
        migrations.AddField(
            model_name='plancuenta',
            name='parentId',
            field=models.ForeignKey(blank=True, db_column='idparentId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idparentId', to='app_contabilidad_planCuentas.plancuenta', verbose_name='Cuenta Raiz o Cuenta Padre'),
        ),
        migrations.AddField(
            model_name='detallecuentasplancuenta',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_contabilidad_planCuentas.plancuenta'),
        ),
        migrations.AddField(
            model_name='recibo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_reg_empresa.empresa'),
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='receipt',
            field=models.ForeignKey(limit_choices_to={'voucher_type__in': ['01', '08']}, on_delete=django.db.models.deletion.CASCADE, to='app_contabilidad_planCuentas.recibo', verbose_name='Tipo de comprobante'),
        ),
        migrations.AddField(
            model_name='vouchererrors',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_contabilidad_planCuentas.recibo'),
        ),
        migrations.AlterUniqueTogether(
            name='atsperiodo',
            unique_together={('config', 'periodo', 'anio')},
        ),
    ]
