# Generated by Django 4.0.2 on 2024-10-28 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reg_empresa', '0002_empresa_business_name_empresa_description_and_more'),
        ('app_contabilidad_planCuentas', '0003_alter_recibo_options_alter_vouchererrors_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexotransaccional',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_reg_empresa.empresa', verbose_name='Compañia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anexotransaccional',
            name='receipt',
            field=models.ForeignKey(blank=True, limit_choices_to={'voucher_type__in': ['01', '08']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_contabilidad_planCuentas.recibo', verbose_name='Tipo de comprobante'),
        ),
    ]
