# Generated by Django 4.0.2 on 2024-11-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad_planCuentas', '0004_anexotransaccional_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexotransaccional',
            name='create_electronic_invoice',
            field=models.BooleanField(default=True, verbose_name='Crear factura electrónica'),
        ),
    ]
