# Generated by Django 4.0.2 on 2024-11-19 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reg_empresa', '0002_empresa_business_name_empresa_description_and_more'),
        ('app_contabilidad_planCuentas', '0005_anexotransaccional_create_electronic_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexotransaccional',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_reg_empresa.empresa', verbose_name='Seleccionar empresa'),
        ),
        migrations.AlterField(
            model_name='anexotransaccional',
            name='receipt',
            field=models.ForeignKey(limit_choices_to={'voucher_type__in': ['01', '08']}, on_delete=django.db.models.deletion.CASCADE, to='app_contabilidad_planCuentas.recibo', verbose_name='Tipo de comprobante'),
        ),
    ]
