# Generated by Django 4.0.2 on 2024-12-11 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reg_empresa', '0002_empresa_business_name_empresa_description_and_more'),
        ('app_contabilidad_planCuentas', '0006_alter_anexotransaccional_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_reg_empresa.empresa'),
        ),
        migrations.AlterField(
            model_name='anexotransaccional',
            name='comp_numero',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Número comprobante'),
        ),
    ]
