# Generated by Django 4.0.2 on 2024-12-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad_planCuentas', '0007_recibo_empresa_alter_anexotransaccional_comp_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexotransaccional',
            name='secuencia',
            field=models.CharField(default=0, max_length=9),
        ),
    ]
