# Generated by Django 4.0.2 on 2024-12-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad_planCuentas', '0008_alter_anexotransaccional_secuencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anexotransaccional',
            old_name='secuencia',
            new_name='comp_secuencia',
        ),
        migrations.AddField(
            model_name='anexotransaccional',
            name='estab_serie',
            field=models.CharField(default=0, max_length=6, verbose_name='Establecimiento - Serie'),
        ),
        migrations.AlterField(
            model_name='anexotransaccional',
            name='comp_serie',
            field=models.CharField(default=0, max_length=6, verbose_name='N. Serie/Secuencia:'),
        ),
    ]
