# Generated by Django 4.0.2 on 2024-12-16 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad_planCuentas', '0009_rename_secuencia_anexotransaccional_comp_secuencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='sequence',
            field=models.PositiveIntegerField(default=0, verbose_name='Secuencia actual'),
        ),
        migrations.AlterField(
            model_name='vouchererrors',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vouchererrors',
            name='datetime_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
