# Generated by Django 4.0.2 on 2025-01-04 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reg_empresa', '0002_empresa_business_name_empresa_description_and_more'),
        ('app_contabilidad_planCuentas', '0010_alter_recibo_sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encabezadocuentasplancuenta',
            name='empresa',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app_reg_empresa.empresa', verbose_name='Seleccionar Empresa:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encabezadocuentasplancuenta',
            name='reg_control',
            field=models.CharField(default='RT', max_length=400, verbose_name='Tipo de Registro'),
        ),
        migrations.AlterField(
            model_name='anexotransaccional',
            name='receipt',
            field=models.ForeignKey(limit_choices_to={'voucher_type__in': ['01', '07']}, on_delete=django.db.models.deletion.CASCADE, to='app_contabilidad_planCuentas.recibo', verbose_name='Tipo de comprobante'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='voucher_type',
            field=models.CharField(choices=[('01', 'FACTURA'), ('04', 'NOTA DE CRÉDITO'), ('08', 'TICKET DE VENTA'), ('07', 'COMPROBANTE DE RETENCIÓN')], max_length=20, verbose_name='Tipo de Comprobante'),
        ),
    ]
