# Generated by Django 4.0.2 on 2025-04-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad_planCuentas', '0011_encabezadocuentasplancuenta_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancuenta',
            name='nombre',
            field=models.CharField(default=2, max_length=150, verbose_name='Nombre de la Cuenta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plancuenta',
            name='periodo',
            field=models.CharField(max_length=150, verbose_name='Periodo (Año)'),
        ),
        migrations.AlterField(
            model_name='plancuenta',
            name='tipo_cuenta',
            field=models.CharField(max_length=150, verbose_name='Tipo de Cuenta'),
        ),
    ]
