# Generated by Django 4.0.2 on 2025-06-25 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_proveedor', '0001_initial'),
        ('app_contabilidad_planCuentas', '0013_encabezadocuentasplancuenta_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encabezadocuentasplancuenta',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_proveedor.proveedor', verbose_name='Seleccionar Proveedor '),
        ),
    ]
