# Generated by Django 5.2.4 on 2025-08-12 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad_planCuentas', '0014_alter_encabezadocuentasplancuenta_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexotransaccional',
            name='receipt',
            field=models.ForeignKey(limit_choices_to={'voucher_type__in': ['01', '08']}, on_delete=django.db.models.deletion.CASCADE, to='app_contabilidad_planCuentas.recibo', verbose_name='Tipo de comprobante'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='voucher_type',
            field=models.CharField(choices=[('01', 'FACTURA'), ('04', 'NOTA DE CRÉDITO'), ('07', 'COMPROBANTE DE RETENCIÓN'), ('08', 'TICKET DE VENTA')], max_length=20, verbose_name='Tipo de Comprobante'),
        ),
    ]
