# Generated by Django 5.2.4 on 2025-08-29 00:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad_planCuentas', '0015_alter_anexotransaccional_receipt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_receptor', models.CharField(max_length=13, verbose_name='ID Receptor')),
                ('nombre_receptor', models.CharField(max_length=200, verbose_name='Nombre Receptor')),
                ('periodicidad', models.CharField(choices=[('mensual', 'Mensual'), ('semestral', 'Semestral')], default='mensual', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuración ATS',
                'verbose_name_plural': 'Configuraciones ATS',
                'db_table': 'tb_configATS',
            },
        ),
        migrations.CreateModel(
            name='ATSImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_xml', models.FileField(upload_to='ats_importaciones/')),
                ('periodo_importado', models.CharField(max_length=20)),
                ('informante', models.CharField(max_length=200)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('total_compras', models.IntegerField(default=0)),
                ('total_ventas', models.IntegerField(default=0)),
                ('total_anulados', models.IntegerField(default=0)),
                ('estado', models.CharField(default='importado', max_length=20)),
            ],
            options={
                'verbose_name': 'Importación ATS',
                'verbose_name_plural': 'Importaciones ATS',
                'db_table': 'tb_importacionATS',
            },
        ),
        migrations.CreateModel(
            name='ATSPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=20, verbose_name='Período')),
                ('anio', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2050)])),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('enviado', 'Enviado')], default='pendiente', max_length=10)),
                ('fecha_generacion', models.DateTimeField(blank=True, null=True)),
                ('archivo_xml', models.FileField(blank=True, null=True, upload_to='ats_xml/')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contabilidad_planCuentas.atsconfig')),
            ],
            options={
                'verbose_name': 'Período ATS',
                'verbose_name_plural': 'Períodos ATS',
                'db_table': 'tb_periodoATS',
                'unique_together': {('config', 'periodo', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='ATSCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_id', models.CharField(max_length=2, verbose_name='TP ID')),
                ('no_identif', models.CharField(max_length=13, verbose_name='No. Identif.')),
                ('proveedor', models.CharField(max_length=200, verbose_name='Proveedor')),
                ('sust_tp', models.CharField(max_length=10, verbose_name='Sust. TP')),
                ('no_doc', models.CharField(max_length=20, verbose_name='# Doc.')),
                ('fecha_emision', models.DateField(verbose_name='F.Emisión')),
                ('valor_objeto_iva', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='V.Ito Obj IVA')),
                ('excento', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Excento')),
                ('base_0', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Base 0%')),
                ('base_iva', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Base IVA')),
                ('monto_iva', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('no_retenc', models.CharField(blank=True, max_length=20, verbose_name='# Retenc.')),
                ('rt_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='RT IVA')),
                ('rt_fte', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='RT FTE')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contabilidad_planCuentas.atsperiodo')),
            ],
            options={
                'verbose_name': 'Compra ATS',
                'verbose_name_plural': 'Compras ATS',
                'db_table': 'tb_compraATS',
            },
        ),
        migrations.CreateModel(
            name='ATSAnulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_doc', models.CharField(max_length=2, verbose_name='Tp.Doc')),
                ('fecha_emision', models.DateField(verbose_name='F.Emisión')),
                ('no_documento', models.CharField(max_length=20, verbose_name='# Documento')),
                ('id_emisor', models.CharField(max_length=13, verbose_name='ID. Emisor')),
                ('razon_social_emisor', models.CharField(max_length=200, verbose_name='Razón Social Emisor')),
                ('id_receptor', models.CharField(max_length=13, verbose_name='ID. Receptor')),
                ('razon_social_receptor', models.CharField(max_length=200, verbose_name='Razón Social Receptor')),
                ('clave_acceso', models.CharField(max_length=49, verbose_name='Clave Acceso')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contabilidad_planCuentas.atsperiodo')),
            ],
            options={
                'verbose_name': 'Anulado ATS',
                'verbose_name_plural': 'Anulados ATS',
                'db_table': 'tb_anuladoATS',
            },
        ),
        migrations.CreateModel(
            name='ATSVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_id', models.CharField(max_length=2, verbose_name='TP ID')),
                ('no_identif', models.CharField(max_length=13, verbose_name='No. Identif.')),
                ('cliente', models.CharField(max_length=200, verbose_name='Cliente')),
                ('tp_comp', models.CharField(max_length=10, verbose_name='Tp.Comp.')),
                ('no_docs', models.CharField(max_length=20, verbose_name='# Docs.')),
                ('base_imp_0', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Base Imp. 0%')),
                ('base_imp_iva', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Base Imp. IVA')),
                ('monto_iva', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto IVA')),
                ('no_objeto_iva', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='No Objeto IVA')),
                ('ret_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ret. IVA')),
                ('ret_fte', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ret. Fte.')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contabilidad_planCuentas.atsperiodo')),
            ],
            options={
                'verbose_name': 'Venta ATS',
                'verbose_name_plural': 'Ventas ATS',
                'db_table': 'tb_ventaATS',
            },
        ),
    ]
