# Generated by Django 4.0.2 on 2025-09-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad_planCuentas', '0016_atsconfig_atsimportacion_atsperiodo_atscompra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexotransaccional',
            name='estab',
            field=models.CharField(default=0, max_length=6, verbose_name='Establecimiento'),
        ),
    ]
