# Generated by Django 4.0.2 on 2026-02-24 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reg_empresa', '0010_alter_piscinas_cuenta_suministros_and_more'),
        ('app_contabilidad_planCuentas', '0017_alter_anexotransaccional_estab'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=False)),
                ('cerrado', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reg_empresa.empresa')),
            ],
            options={
                'ordering': ['-anio'],
                'unique_together': {('empresa', 'anio')},
            },
        ),
    ]
