# Generated by Django 4.0.2 on 2025-06-25 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Módulo',
                'verbose_name_plural': 'Tipos de Módulos',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('icono', models.CharField(default='fas fa-cog', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.tipomodulo')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='GrupoModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.modulo')),
            ],
            options={
                'verbose_name': 'Grupo Módulo',
                'verbose_name_plural': 'Grupos Módulos',
                'unique_together': {('grupo', 'modulo')},
            },
        ),
    ]
