# Generated by Django 4.0.2 on 2025-06-25 15:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_tipomodulo_modulo_grupomodulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupomodulo',
            options={'verbose_name': 'Grupo-Módulo', 'verbose_name_plural': 'Grupos-Módulos'},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['tipo__orden', 'orden', 'nombre'], 'verbose_name': 'Módulo', 'verbose_name_plural': 'Módulos'},
        ),
        migrations.AlterModelOptions(
            name='tipomodulo',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Tipo de Módulo', 'verbose_name_plural': 'Tipos de Módulos'},
        ),
        migrations.AddField(
            model_name='modulo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tipomodulo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='tipomodulo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tipomodulo',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tipomodulo',
            name='orden',
            field=models.PositiveIntegerField(default=1, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='grupomodulo',
            name='fecha_asignacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='icono',
            field=models.CharField(default='fas fa-cog', max_length=50, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='orden',
            field=models.PositiveIntegerField(default=1, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.tipomodulo', verbose_name='Tipo de Módulo'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='url',
            field=models.CharField(default=2, max_length=200, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipomodulo',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tipomodulo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
    ]
