# Generated by Django 5.2.4 on 2026-02-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_alter_user_options_user_email_reset_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupomodulo',
            name='can_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grupomodulo',
            name='can_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grupomodulo',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grupomodulo',
            name='can_view',
            field=models.BooleanField(default=True),
        ),
    ]
