# Generated by Django 5.2.4 on 2026-02-21 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0006_alter_user_options_alter_modulo_activo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='modulo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='icono',
            field=models.CharField(default='fas fa-cog', max_length=50, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='orden',
            field=models.PositiveIntegerField(default=1, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.tipomodulo', verbose_name='Tipo de Módulo'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='url',
            field=models.CharField(max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='tipomodulo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='tipomodulo',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tipomodulo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tipomodulo',
            name='orden',
            field=models.PositiveIntegerField(default=1, verbose_name='Orden'),
        ),
    ]
