# Generated by Django 5.2.4 on 2026-03-06 02:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnioDieta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_dieta', models.IntegerField(blank=True, null=True, verbose_name='Ingresar Año')),
            ],
            options={
                'verbose_name': 'AnioDieta',
                'verbose_name_plural': '1. Años Dieta',
                'db_table': 'db_anio_dieta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DescripcionDieta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Escaneo ')),
                ('descripcion', models.CharField(max_length=400, verbose_name='Novedad de la Dieta ')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='descripcionDieta/%Y/%m/%d', verbose_name='Archivo Escaneado ')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'db_table': 'tb_registro',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DiaDietaRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha Dieta')),
                ('tip_dieta', models.BooleanField(default=True, verbose_name='Si es Dieta de Piscinas Seleccione ')),
            ],
            options={
                'verbose_name': 'DiaDietaRegistro',
                'verbose_name_plural': '3. Dias de Dietas Registros',
                'db_table': 'db_dia_dieta_reg',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='MesDieta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_dieta', models.CharField(blank=True, max_length=250, null=True, verbose_name='Mes de Dieta')),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'MesDieta',
                'verbose_name_plural': '2. Meses Dietas',
                'db_table': 'db_mes_dieta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleDiaDieta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('insumo1', models.IntegerField(default=0)),
                ('gramaje1', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('insumo2', models.IntegerField(default=0)),
                ('gramaje2', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('insumo3', models.IntegerField(default=0)),
                ('gramaje3', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('insumo4', models.IntegerField(default=0)),
                ('gramaje4', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('balanceado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_categoria.producto')),
            ],
            options={
                'verbose_name': 'Detalle del día dieta',
                'verbose_name_plural': 'Detalle del día dietas',
                'db_table': 'db_dia_dieta_detalle',
                'ordering': ['id'],
            },
        ),
    ]
