# Generated by Django 4.0.2 on 2026-01-12 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dieta_reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallediadieta',
            options={'ordering': ['id'], 'verbose_name': 'Detalle del día dieta', 'verbose_name_plural': 'Detalle del día dietas'},
        ),
    ]
