# Generated by Django 5.2.4 on 2026-03-06 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_dieta_reg', '0001_initial'),
        ('app_piscinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallediadieta',
            name='piscinas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_piscinas.piscinas', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='detallediadieta',
            name='dieta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dieta_reg.diadietaregistro'),
        ),
        migrations.AddField(
            model_name='mesdieta',
            name='anio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_dieta_reg.aniodieta'),
        ),
        migrations.AddField(
            model_name='diadietaregistro',
            name='mes_dieta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dieta_reg.mesdieta', verbose_name='Mes de Dieta'),
        ),
    ]
