# Generated by Django 4.0.2 on 2026-03-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dieta_reg', '0002_alter_detallediadieta_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallediadieta',
            name='gramaje1',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detallediadieta',
            name='gramaje2',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detallediadieta',
            name='gramaje3',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detallediadieta',
            name='gramaje4',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
    ]
