# Generated by Django 5.2.4 on 2026-03-06 02:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_categoria', '0001_initial'),
        ('app_contabilidad_planCuentas', '0002_initial'),
        ('app_proveedor', '0001_initial'),
        ('app_reg_empresa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fecha_ingreso', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Registro ')),
                ('numero_guia', models.CharField(blank=True, max_length=250, null=True, verbose_name='Numero Factura, Guia o Descripción ')),
                ('responsable_ingreso', models.CharField(blank=True, max_length=250, null=True, verbose_name='Persona Responsable ')),
                ('observacion', models.TextField(blank=True, default='Sin Novedades', null=True, verbose_name='Observación ')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Subtotal ')),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='IVA ')),
                ('ivacalc', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='IVA Calc ')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Total ')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_proveedor.proveedor', verbose_name='Proveedor ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'InvoiceStock',
                'verbose_name_plural': 'InvoiceStock',
                'db_table': 'invoiceStock',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Total_Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Stock')),
                ('cod_contable', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Contable')),
                ('nombre_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reg_empresa.empresa', verbose_name='Empresa')),
                ('nombre_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_categoria.producto', verbose_name='Producto')),
                ('plan_cuenta', models.ForeignKey(blank=True, help_text='Seleccione la cuenta contable para este producto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_contabilidad_planCuentas.plancuenta', verbose_name='Plan de Cuentas')),
            ],
            options={
                'verbose_name': 'Stock Total',
                'verbose_name_plural': 'Stocks Totales',
                'db_table': 'stock_total',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto_Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, default='INGRESO', max_length=8, null=True)),
                ('piscinas', models.CharField(blank=True, default='Todas las Piscinas', max_length=250, null=True)),
                ('cantidad_usar', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Cantidad en ')),
                ('cantidad_ingreso', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Cantidad de Ingreso en ')),
                ('cantidad_egreso', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Cantidad de Egreso en ')),
                ('fecha_ingreso', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Registro ')),
                ('numero_guia', models.CharField(blank=True, max_length=250, null=True, verbose_name='Numero Guia o Descripción ')),
                ('responsable_ingreso', models.CharField(blank=True, max_length=250, null=True, verbose_name='Persona Responsable ')),
                ('observacion', models.TextField(blank=True, default='Sin Novedades', null=True, verbose_name='Observación ')),
                ('activo', models.BooleanField(default=True, verbose_name='Registro Activo ')),
                ('detalle_dieta_id', models.IntegerField(blank=True, null=True, verbose_name='Id Detalle Dieta ')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='Subtotal ')),
                ('iva', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='IVA ')),
                ('ivacalc', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='IVA Calc ')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='Total ')),
                ('invoice_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_detalle_stock.invoicestock', verbose_name='Factura')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_proveedor.proveedor', verbose_name='Proveedor ')),
                ('producto_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_detalle_stock.total_stock', verbose_name='Producto Stock ')),
            ],
            options={
                'verbose_name': 'Kardex',
                'verbose_name_plural': 'Kardexs',
                'db_table': 'stock_prod',
                'ordering': ['fecha_ingreso', '-piscinas'],
            },
        ),
    ]
