# Generated by Django 4.0.2 on 2024-07-12 17:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_categoria', '0001_initial'),
        ('app_reg_empresa', '0001_initial'),
        ('app_proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fecha_ingreso', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Registro ')),
                ('numero_guia', models.CharField(blank=True, max_length=250, null=True, verbose_name='Numero Factura, Guia o Descripción ')),
                ('responsable_ingreso', models.CharField(blank=True, max_length=250, null=True, verbose_name='Persona Responsable ')),
                ('observacion', models.TextField(blank=True, default='Sin Novedades', null=True, verbose_name='Observación ')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Subtotal ')),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='IVA ')),
                ('ivacalc', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='IVA Calc ')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Total ')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_proveedor.proveedor', verbose_name='Proveedor ')),
            ],
            options={
                'verbose_name': 'InvoiceStock',
                'verbose_name_plural': 'InvoiceStock',
                'db_table': 'invoiceStock',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Total_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Stock')),
                ('nombre_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reg_empresa.empresa', verbose_name='Empresa')),
                ('nombre_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_categoria.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Stock Total',
                'verbose_name_plural': 'Stocks Totales',
                'db_table': 'stock_total',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, default='INGRESO', max_length=8, null=True)),
                ('piscinas', models.CharField(blank=True, default='Todas las Piscinas', max_length=250, null=True)),
                ('cantidad_usar', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Cantidad en ')),
                ('cantidad_ingreso', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Cantidad de Ingreso en ')),
                ('cantidad_egreso', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Cantidad de Egreso en ')),
                ('fecha_ingreso', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Registro ')),
                ('numero_guia', models.CharField(blank=True, max_length=250, null=True, verbose_name='Numero Guia o Descripción ')),
                ('responsable_ingreso', models.CharField(blank=True, max_length=250, null=True, verbose_name='Persona Responsable ')),
                ('observacion', models.TextField(blank=True, default='Sin Novedades', null=True, verbose_name='Observación ')),
                ('activo', models.BooleanField(default=True, verbose_name='Registro Activo ')),
                ('detalle_dieta_id', models.IntegerField(blank=True, null=True, verbose_name='Id Detalle Dieta ')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='Subtotal ')),
                ('iva', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='IVA ')),
                ('ivacalc', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='IVA Calc ')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='Total ')),
                ('invoice_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_detalle_stock.invoicestock', verbose_name='Factura')),
                ('producto_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_detalle_stock.total_stock', verbose_name='Producto Stock ')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_proveedor.proveedor', verbose_name='Proveedor ')),
            ],
            options={
                'verbose_name': 'Kardex',
                'verbose_name_plural': 'Kardexs',
                'db_table': 'stock_prod',
                'ordering': ['fecha_ingreso', '-piscinas'],
            },
        ),
    ]
