# Generated by Django 4.0.2 on 2025-11-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_detalle_stock', '0002_invoicestock_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_stock',
            name='cod_contable',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Contable'),
        ),
    ]
