# Generated by Django 4.0.2 on 2025-11-25 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad_planCuentas', '0017_alter_anexotransaccional_estab'),
        ('app_detalle_stock', '0003_total_stock_cod_contable'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_stock',
            name='plan_cuenta',
            field=models.ForeignKey(blank=True, help_text='Seleccione la cuenta contable para este producto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_contabilidad_planCuentas.plancuenta', verbose_name='Plan de Cuentas'),
        ),
    ]
