# Generated by Django 5.2.4 on 2026-03-05 21:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(blank=True, help_text='Ej: localpasaje (sera el subdominio: localpasaje.tudominio.com)', max_length=30, null=True, unique=True, verbose_name='Nombre del esquema')),
                ('ruc', models.CharField(blank=True, max_length=13, null=True, verbose_name='Numero de RUC')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Empresa')),
                ('business_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Razón social')),
                ('tradename', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Comercial')),
                ('direccion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Direccion ')),
                ('main_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección del Establecimiento Matriz')),
                ('establishment_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección del Establecimiento Emisor')),
                ('siglas', models.CharField(max_length=150, verbose_name='Siglas ')),
                ('establishment_code', models.CharField(blank=True, max_length=3, null=True, verbose_name='Código del Establecimiento Emisor')),
                ('issuing_point_code', models.CharField(blank=True, max_length=3, null=True, verbose_name='Código del Punto de Emisión')),
                ('special_taxpayer', models.CharField(blank=True, max_length=13, null=True, verbose_name='Contribuyente Especial (Número de Resolución)')),
                ('aperturada', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Apertura ')),
                ('actividad', models.CharField(blank=True, max_length=150, null=True, verbose_name='Actividad ')),
                ('estado', models.BooleanField(default=True, verbose_name='Seleccionar el Estado')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo_comp/%Y/%m/%d', verbose_name='Logotipo de la empresa')),
                ('obligated_accounting', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=2, verbose_name='Obligado a Llevar Contabilidad')),
                ('environment_type', models.PositiveIntegerField(choices=[(1, 'PRUEBAS'), (2, 'PRODUCCIÓN')], default=1, verbose_name='Tipo de Ambiente')),
                ('emission_type', models.PositiveIntegerField(choices=[(1, 'Emisión Normal')], default=1, verbose_name='Tipo de Emisión')),
                ('retention_agent', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=2, verbose_name='Agente de Retención')),
                ('mobile', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono celular')),
                ('phone', models.CharField(blank=True, max_length=9, null=True, verbose_name='Teléfono convencional')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('website', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección de página web')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='IVA')),
                ('vat_percentage', models.IntegerField(choices=[(0, '0%'), (2, '12%'), (3, '14%'), (4, '15%'), (5, '5%'), (6, 'No Objeto de Impuesto'), (7, 'Exento de IVA'), (8, 'IVA diferenciado'), (10, '13%')], default=4, verbose_name='Porcentaje del IVA')),
                ('electronic_signature', models.FileField(blank=True, null=True, upload_to='company/%Y/%m/%d', verbose_name='Firma electrónica (Archivo P12)')),
                ('electronic_signature_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Clave de firma electrónica')),
                ('email_host', models.CharField(blank=True, default='smtp.gmail.com', max_length=30, null=True, verbose_name='Servidor de correo')),
                ('email_port', models.IntegerField(blank=True, default=587, null=True, verbose_name='Puerto del servidor de correo')),
                ('email_host_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username del servidor de correo')),
                ('email_host_password', models.CharField(blank=True, max_length=30, null=True, verbose_name='Password del servidor de correo')),
                ('scheme', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='app_tenant.scheme', verbose_name='Esquema')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'tb_empresa',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('schema_name', models.CharField(max_length=30, unique=True, verbose_name='Nombre del schema')),
                ('activo', models.BooleanField(default=True)),
                ('cerrado', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='app_reg_empresa.empresa', verbose_name='Empresa')),
                ('scheme', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_tenant.scheme')),
            ],
            options={
                'verbose_name': 'Periodo Fiscal',
                'verbose_name_plural': 'Periodos Fiscales',
                'db_table': 'tb_periodo_fiscal',
                'unique_together': {('empresa', 'anio')},
            },
        ),
    ]
