# Generated by Django 4.0.2 on 2024-10-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reg_empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='business_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Razón social'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='electronic_signature',
            field=models.FileField(blank=True, null=True, upload_to='company/%Y/%m/%d', verbose_name='Firma electrónica (Archivo P12)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='electronic_signature_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Clave de firma electrónica'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=30, null=True, verbose_name='Servidor de correo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Password del servidor de correo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_host_user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Username del servidor de correo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_port',
            field=models.IntegerField(blank=True, default=587, null=True, verbose_name='Puerto del servidor de correo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='emission_type',
            field=models.PositiveIntegerField(choices=[(1, 'Emisión Normal')], default=1, verbose_name='Tipo de Emisión'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='environment_type',
            field=models.PositiveIntegerField(choices=[(1, 'PRUEBAS'), (2, 'PRODUCCIÓN')], default=1, verbose_name='Tipo de Ambiente'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='establishment_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección del Establecimiento Emisor'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='establishment_code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Código del Establecimiento Emisor'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='issuing_point_code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Código del Punto de Emisión'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='IVA'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='main_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección del Establecimiento Matriz'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono celular'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='obligated_accounting',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=2, verbose_name='Obligado a Llevar Contabilidad'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='phone',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Teléfono convencional'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='retention_agent',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=2, verbose_name='Agente de Retención'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='special_taxpayer',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Contribuyente Especial (Número de Resolución)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tradename',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Comercial'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='vat_percentage',
            field=models.IntegerField(choices=[(0, '0%'), (2, '12%'), (3, '14%'), (4, '15%'), (5, '5%'), (6, 'No Objeto de Impuesto'), (7, 'Exento de IVA'), (8, 'IVA diferenciado'), (10, '13%')], default=4, verbose_name='Porcentaje del IVA'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='website',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección de página web'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='actividad',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Actividad '),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Direccion '),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Seleccionar el Estado'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_comp/%Y/%m/%d', verbose_name='Logotipo de la empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre Empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ruc',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Numero de RUC'),
        ),
    ]
