# Generated by Django 4.0.2 on 2025-05-19 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reg_empresa', '0002_empresa_business_name_empresa_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('densidad_siembra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Densidad de siembra (larvas/m²)')),
                ('cantidad_larvas', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de larvas')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('piscina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='app_reg_empresa.piscinas', verbose_name='Piscina')),
            ],
            options={
                'verbose_name': 'Ciclo',
                'verbose_name_plural': 'Ciclos',
                'db_table': 'tb_ciclo',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TipoCosto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Costo',
                'verbose_name_plural': 'Tipos de Costos',
                'db_table': 'tb_tipo_costo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cosecha', models.DateField(verbose_name='Fecha de cosecha')),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad en kilogramos')),
                ('precio_venta_kg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio de venta por kilogramo')),
                ('talla_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Talla promedio en gramos')),
                ('cliente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cliente')),
                ('factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Factura')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('usuario_registro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario que registra')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producciones', to='app_reg_empresa.ciclo', verbose_name='Ciclo')),
                ('piscina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producciones', to='app_reg_empresa.piscinas', verbose_name='Piscina')),
            ],
            options={
                'verbose_name': 'Producción',
                'verbose_name_plural': 'Producciones',
                'db_table': 'tb_produccion',
                'ordering': ['-fecha_cosecha'],
            },
        ),
        migrations.CreateModel(
            name='CostoOperativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('comprobante', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de factura o comprobante')),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Proveedor')),
                ('usuario_registro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario que registra')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('piscina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='app_reg_empresa.piscinas', verbose_name='Piscina')),
                ('tipo_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costos', to='app_reg_empresa.tipocosto', verbose_name='Tipo de Costo')),
            ],
            options={
                'verbose_name': 'Costo Operativo',
                'verbose_name_plural': 'Costos Operativos',
                'db_table': 'tb_costo_operativo',
                'ordering': ['-fecha', 'piscina'],
            },
        ),
    ]
