# Generated by Django 4.0.2 on 2025-05-22 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_proveedor', '0001_initial'),
        ('app_reg_empresa', '0003_ciclo_tipocosto_produccion_costooperativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costooperativo',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_operativos', to='app_proveedor.proveedor'),
        ),
    ]
