# Generated by Django 4.0.2 on 2025-06-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reg_empresa', '0004_alter_costooperativo_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produccion',
            old_name='cliente',
            new_name='cliente',
        ),
    ]
