# Generated by Django 4.0.2 on 2025-07-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reg_empresa', '0005_rename_app_cliente_produccion_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='piscinas',
            name='with_tax',
            field=models.BooleanField(default=True, verbose_name='¿Se cobra impuesto?'),
        ),
    ]
