# Generated by Django 4.0.2 on 2025-07-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reg_empresa', '0006_piscinas_with_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='piscinas',
            name='inventoried',
            field=models.BooleanField(default=True, verbose_name='¿Es inventariado?'),
        ),
    ]
