# Generated by Django 5.2.4 on 2025-12-02 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad_planCuentas', '0017_alter_anexotransaccional_estab'),
        ('app_reg_empresa', '0007_piscinas_inventoried'),
    ]

    operations = [
        migrations.AddField(
            model_name='piscinas',
            name='cuenta_suministros',
            field=models.ForeignKey(blank=True, help_text='Subcuenta de suministros (ej: 102030101002 SUMINISTROS)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piscinas_suministros', to='app_contabilidad_planCuentas.plancuenta', verbose_name='Cuenta Suministros'),
        ),
        migrations.AddField(
            model_name='piscinas',
            name='plan_cuenta',
            field=models.ForeignKey(blank=True, help_text='Cuenta contable principal de la piscina (ej: 102030101 PISCINA# 21)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piscinas', to='app_contabilidad_planCuentas.plancuenta', verbose_name='Plan de Cuentas'),
        ),
    ]
