# Generated by Django 5.2.4 on 2026-01-07 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reg_empresa', '0008_piscinas_cuenta_suministros_piscinas_plan_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiscinaHistorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fue_piscina', models.BooleanField(default=False)),
                ('fue_precria', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('piscina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='app_reg_empresa.piscinas')),
            ],
            options={
                'db_table': 'tb_piscina_historial',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
