# Generated by Django 4.0.2 on 2026-02-02 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad_planCuentas', '0017_alter_anexotransaccional_estab'),
        ('app_reg_empresa', '0009_piscinahistorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piscinas',
            name='cuenta_suministros',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piscinas_suministros', to='app_contabilidad_planCuentas.plancuenta', verbose_name='Cuenta de Suministros'),
        ),
        migrations.AlterField(
            model_name='piscinas',
            name='plan_cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piscinas', to='app_contabilidad_planCuentas.plancuenta', verbose_name='Plan de Cuentas'),
        ),
    ]
